/* Site UI localization. User creations, credentials, filenames and JSON stay intact. */
(function(){
'use strict';
const en={
'Grandpas Land 爷爷的地 — 官方网站':'Grandpas Land — Official Website',
'跳到主要内容':'Skip to main content','游戏':'Game','AI 工坊':'AI Workshop','分享广场':'Community','使用文档':'Guide','主导航':'Main navigation',
'让世界，':'Let your world','生长出你的':'grow with','想象。':'imagination.',
'爷爷留下的土地，由你来传承。与朋友建设、探索，也用 AI 为这片世界写下新的名字、故事和节日。':'Carry on the legacy of the land Grandpa left behind. Build and explore with friends, and use AI to add new names, stories and festivals to your world.',
'开始创造':'Start creating','走进爷爷的地':'Explore the game','自己的 API Key':'Your own API key','八类世界内容':'Eight library types','世界概念插画 · 营地与远方':'World concept art · A camp and a distant world',
'把灵感，种进世界。':'Plant your ideas in the world.','从一句描述，到一份可以带进游戏的内容库。':'Turn a simple description into a library you can bring into the game.','AI 资产工坊':'AI Asset Workshop',
'描述名字的风格，或构思一段新故事。生成后编辑预览、检查格式，再下载自己的资产库。':'Describe a naming style or imagine a new story. Edit the preview, check its format, and download your library.',
'从一个想法开始':'Begin with an idea','发现玩家创作的世界内容，按类型、时间与标签查找。打开详情，预览并下载喜欢的作品。':'Discover player-created libraries by type, date and tag. Open a creation to preview and download it.','看看大家的世界':'Discover other worlds','带进你的游戏':'Bring it into your game',
'找到资产文件夹，了解内容格式和使用方法。让新的名字与故事，成为下一个世界的一部分。':'Find the library folder and learn how to use the files. Make new names and stories part of your next world.','查看使用指南':'Read the guide','一片土地，':'One little land,','许多种生活的可能。':'many ways to live.',
'你继承了爷爷留下的一片土地。开垦、建造、结识居民，与朋友在同一片世界里冒险。这片土地的故事，也可以由你亲手续写。':'You inherit a piece of land from Grandpa. Cultivate it, build, meet the locals and explore the same world with friends. Its next chapter can be yours to write.',
'自定义城市、人物、公司与家族的名字，再为世界创作支线、事件、节日和特定 NPC 内容。可执行的游戏效果以游戏当前支持的规则为准。':'Customize city, character, company and family names, then create quests, events, festivals and special NPC content. Gameplay effects depend on the rules currently supported by the game.',
'多人同局':'Play together','开放世界':'Open world','建设与冒险':'Building & adventure','自定义世界内容':'Custom world content','在下一段旅程里，':'See you in','相见。':'the next chapter.',
'Steam 商店页即将开放。上线后，这里会提供商店与愿望单入口。':'The Steam store page is coming soon. Store and wishlist links will appear here when it opens.','Steam · 敬请期待':'Steam · Coming soon','世界的不同侧面。':'Different sides of the world.',
'从海风吹拂的港口，到灯火温暖的小店，再到远方的城堡。':'From a breezy harbor and a warmly lit shop to a castle on the horizon.','世界概念插画':'World concept art','海风与远航':'Sea breeze & voyages','小径的尽头，是更辽阔的世界。':'A wider world awaits at the end of the path.','烟火与日常':'The warmth of everyday life','街角的一盏灯，也藏着新的故事。':'Even a light on the corner holds a new story.','城堡与冒险':'Castles & adventures','当远方响起号角，新的篇章展开。':'A distant horn announces a new chapter.','© 2026 Grandpas Land · 爷爷的地':'© 2026 Grandpas Land',
'爷爷留下的土地，由你来传承。在 Grandpas Land 的 AI 工坊创造名字、支线、事件与节日，分享你的世界内容。':'Carry on Grandpa’s legacy. Create names, quests, events and festivals in the Grandpas Land AI Workshop, and share your world content.',
'树荫下的营地，远处是湖泊、石桥与山间城堡的世界概念插画':'World concept art: a shaded campsite overlooking a lake, stone bridge and mountain castle','打开海港概念插画大图':'Open the harbor concept art','花草环绕的海边步道、蓝色港湾、帆船与灯塔':'A flower-lined coastal path, a blue harbor, sailboats and a lighthouse','打开面包店概念插画大图':'Open the bakery concept art','阳光照进木制面包店，店外是鲜花与小镇的石板街道':'Sunlight in a wooden bakery overlooking flowers and a cobbled town street','打开城堡概念插画大图':'Open the castle concept art','山脉下的城堡与旗帜，城墙外是一片围城营地':'A castle and banners beneath the mountains, with a siege camp outside the walls',
'AI 资产工坊 — Grandpas Land':'AI Asset Workshop — Grandpas Land','写下一个想法，为世界添一点不同。使用自己的 API Key，生成可导入游戏的内容库。':'Write down an idea and make your world a little different. Use your own API key to generate a library for the game.','连接你的 AI':'Connect your AI','接口地址 · OpenAI 兼容格式':'Endpoint · OpenAI-compatible','模型名称':'Model name','在此设备记住 Key':'Remember the key on this device',
'默认仅本次使用。Key 从浏览器发送给你填写的 AI 服务商，不经过本站。请核对接口地址，勿在公共设备记住 Key。':'Used only for this visit by default. Your browser sends the key directly to your chosen AI provider. Check the endpoint and do not save keys on shared devices.','清除已保存的 Key':'Clear saved key','接口与连接说明 ↗':'Connection guide ↗','选择要种下的灵感':'Choose your inspiration','资产类型':'Library type','城市名库':'City names','NPC 名字库':'NPC names','公司名库':'Company names','家族名库':'Family names','支线库':'Quests','事件库':'Events','节日库':'Festivals','特定 NPC 库':'Special NPCs','库名 · 下载文件名称':'Library name · Download filename','名字数量':'Number of names','你想要什么样的名字？':'What kind of names do you want?','内容描述 / 提示词':'Description / Prompt','条目数量':'Number of entries','权重':'Weight','冷却天数':'Cooldown days','节日规则':'Festival rule','周期性':'Periodic','按季节':'By season','每年第几天':'Day of the year','季节':'Season','春季':'Spring','夏季':'Summer','秋季':'Autumn','冬季':'Winter','间隔天数':'Interval in days','持续天数':'Duration in days',
'AI 生成的是游戏内容数据。故事中描述的奖励或行为，须由游戏支持的机制执行。':'AI generates content data. Rewards or actions described in a story require game mechanics that support them.','生成我的资产':'Generate my library','取消生成':'Cancel generation','费用由你的 AI 服务商按用量收取':'Your AI provider charges for usage','灵感的形状':'Your creation','你的新世界，从这里开始。':'Your new world starts here.','完成左侧设置并生成资产。':'Fill in the settings and generate a library.','结果会出现在这里，供你编辑与下载。':'Your result will appear here for editing and download.','资产内容 · 可直接编辑':'Library content · Editable','下载时会校验并保存这里的最新内容。':'Downloading checks and saves the latest content shown here.','下载 .json':'Download .json','校验格式':'Check format','把文件放入下方目录，再在创建世界时选择该库：':'Place the file in this folder, then select the library when creating a world:','分享这份灵感 ↗':'Share this creation ↗','需要帮助？':'Need help? ','查看导入教程':'Read the import guide','。AI 返回内容会经过结构校验，游戏内效果仍需实际验证。':'. AI output is checked for structure; its in-game effects still need testing.','了解资产格式 ↗':'Library format ↗',
'使用自己的 AI API Key 生成 Grandpas Land 世界内容库，编辑预览、校验并下载 JSON 文件。':'Generate Grandpas Land libraries using your own AI key. Edit, validate and download JSON files.','填写 AI 服务商提供的 Key':'Enter the key from your AI provider','例如：江南水乡':'For example: Riverside Towns','江南水乡风格，有青石板、烟雨和渔米之乡的味道，两到三个字。':'Quiet riverside villages, stone paths and misty rain. Short, evocative names.','温泉小镇的夏日支线。帮助旅店老板娘修复温泉，期间与旅行中的画师相识。':'A summer quest in a spa town: help the innkeeper repair a hot spring and meet a traveling painter.',
'分享广场 — Grandpas Land':'Community — Grandpas Land','收集别人的灵感，也分享自己的故事。让每一片土地，都拥有不同的名字。':'Collect ideas and share your own stories. Give every little land a different identity.','搜索作品':'Search creations','全部类型':'All types','全部时间':'All time','最近 7 天':'Last 7 days','最近 30 天':'Last 30 days','最近一年':'Last year','最新发布':'Newest first','最早发布':'Oldest first','评论最多':'Most discussed','分享我的作品':'Share my creation','正在收集大家的灵感…':'Gathering everyone’s ideas…','读取玩家分享，请稍候。':'Loading player creations. Please wait.',
'分享与评论由 GitHub Issues 承载。发布作品、发表评论需要 GitHub 账号；浏览与下载无需登录。':'Creations and comments are hosted on GitHub Issues. A GitHub account is needed to publish or comment; browsing and downloading require no login.','下载资产 ↓':'Download library ↓','GitHub 原帖 ↗':'Original post ↗','作品评论':'Comments','去 GitHub 评论 ↗':'Comment on GitHub ↗','分享一份新的灵感':'Share a new idea','作品名称':'Creation name','选择 .json 资产文件':'Choose a .json library file','作品介绍':'Description','自定义标签 · 用逗号分隔，最多 5 个':'Custom tags · Comma-separated, up to 5',
'文件会先校验，然后打开 GitHub 分享草稿。请在 GitHub 点击提交完成发布。不要在文件或介绍中包含 API Key。':'Your file will be validated before a GitHub draft is prepared. Submit it on GitHub to publish. Do not include API keys in the file or description.','检查并打开发布草稿 ↗':'Validate & prepare draft ↗','较大的文件请在 GitHub 原帖手动附上文件或 JSON 内容。发布后回到广场刷新查看。':'For larger files, attach the file or paste the JSON on GitHub. Refresh this page after publishing.','社区原帖 ↗':'Community on GitHub ↗','发现、预览与下载 Grandpas Land 玩家创作的资产库，按类型、时间和标签查找。':'Discover, preview and download Grandpas Land player libraries by type, date and tag.','搜索作品、介绍或标签…':'Search creations, descriptions or tags…','搜索标题、介绍或标签':'Search titles, descriptions or tags','发布时间':'Published date','排序':'Sort order','按标签筛选':'Filter by tag','关闭作品详情':'Close creation details','关闭分享表单':'Close sharing form','例如：烟雨江南城市名库':'For example: Misty Riverside Town Names','描述风格、内容与适合的世界。':'Describe its style, content and the world it suits.','江南, 古风, 治愈':'riverside, fantasy, cozy',
'使用文档 — Grandpas Land':'Guide — Grandpas Land','把灵感带进游戏。':'Bring your ideas into the game.','从第一份内容库开始。这里有生成、导入与分享的完整步骤。':'Start with your first library. Learn how to generate, import and share it.','快速开始':'Quick start','连接 AI':'Connect AI','导入资产':'Import libraries','JSON 格式':'JSON format','分享与评论':'Sharing & comments','常见问题':'FAQ','文档目录':'Guide navigation','一个文件，一份新的世界内容。':'One file. New world content.','资产库是一个':'A library is a ','文件，装着一组名字或内容条目。游戏创建世界时可以选择使用这些库。':' file containing names or content entries. You can select these libraries when creating a world.','打开':'Open ','，填写 AI 接口、模型名和自己的 API Key。':', then enter your endpoint, model and API key.','选择资产类型、库名，描述想要的内容，点击生成。':'Choose a library type and name, describe what you want, and generate.','检查或编辑结果，下载 JSON。下载按钮会校验并保存预览中的最新内容。':'Review or edit the result and download the JSON. The download button validates and saves the latest preview.','放入对应类型的文件夹，再进入创建世界的内容选择页面。':'Place the file in its type folder and select it in the world creation screen.',
'名字库与内容库可以被游戏读取，但描述中的奖励、对话行为或任务机制不会仅凭文字自动执行。实际效果取决于游戏当前实现的内容系统。':'The game can read name and content libraries. Written descriptions alone do not execute rewards, dialogue actions or quest mechanics. Effects depend on the content systems implemented in the game.','使用自己的 AI 接口':'Use your own AI endpoint','工坊使用 OpenAI 兼容的 Chat Completions 请求格式。默认接口是 DeepSeek 的':'The workshop uses the OpenAI-compatible Chat Completions format. The default DeepSeek endpoint is ','，模型为':', with model ', '。其他服务请以其官方文档中的接口地址与模型名为准。':'. For other providers, use the endpoint and model listed in their official documentation.',
'接口地址必须使用 HTTPS。浏览器会将 Key 作为请求凭据发送到你填写的地址，请确认它属于你信任的 AI 服务商。本站不会代理这次请求。':'Endpoints must use HTTPS. Your browser sends the key as a credential to the address you enter. Make sure it belongs to a provider you trust; this site does not proxy the request.','Key 默认仅在本次页面中使用。只有勾选“在此设备记住 Key”才会写入浏览器本地存储；可随时点击“清除已保存的 Key”。共享设备建议保持不勾选。':'Keys are used only for the current visit by default. Selecting “Remember the key on this device” saves it locally. “Clear saved key” removes it. Leave this option off on shared devices.',
'如果服务商不允许浏览器跨域调用，浏览器会阻止请求。请使用明确支持浏览器请求的接口，或由你信任的服务部署代理。不要把 Key 放进网址、分享文件或评论中。':'If a provider does not allow cross-origin browser requests, the browser blocks them. Use an endpoint that supports browser calls or a proxy you trust. Never put keys in URLs, shared files or comments.','生成费用、请求限额与模型可用性以服务商的当前规定为准。取消或超时仅停止浏览器等待，服务商可能已经处理请求并计费。':'Pricing, limits and model availability are set by your provider. Canceling or timing out only stops the browser from waiting; the request may already have been processed and charged.',
'把资产放进正确的文件夹':'Put libraries in the right folder','当前项目设置的公司名是':'The current project uses company name ','，产品名是':' and product name ', '。Windows 路径如下；发行版如果更改了名称，目录也会改变。':'. The Windows path is below. If the release changes these names, the folder will change too.','按':'Press ','，粘贴上述路径并回车。目录尚未生成时，先运行游戏，或手动创建所需文件夹。':', paste the path above and press Enter. Run the game first, or create the folders manually if they do not exist.','例如，把':'For example, put ','放进':' into ', '。回到创建世界的库选择页面选择它；如果列表未更新，可重新打开该页面或重启游戏。':'. Select it in the world creation screen. Reopen the screen or restart the game if the list has not refreshed.',
'现有世界可能已经把选择的内容保存到存档快照中。修改外部文件不一定会改变已有存档；建议先在新世界中验证。':'Existing worlds may store selected content in save snapshots. Editing external files may not change an existing save. Test the library in a new world first.','与游戏一致的 JSON 格式':'Game-compatible JSON format','名字型：Items':'Name libraries: Items','适用于城市、NPC、公司、家族名字库。每个名字必须是非空文本，不要重复。':'Used for city, NPC, company and family names. Names must be nonempty strings without duplicates.','内容型：Entries':'Content libraries: Entries','适用于支线、事件、节日、特定 NPC 库。字段名区分大小写。':'Used for quests, events, festivals and special NPCs. Field names are case-sensitive.','字段':'Field','作用与默认值':'Purpose & default','名称与描述，工坊要求非空文本。':'Name and description; the workshop requires nonempty strings.','阶段数组，每项含 StageName、Description。缺省为空数组。':'Stage array with StageName and Description in each entry. Defaults to an empty array.','条目标识。生成时补齐，非空标识不能重复。事件关联时需保持稳定。':'Entry identifier. Added during generation; nonempty IDs must be unique and remain stable for event links.','类型标识，例如 Quests、Events。实际运行行为由游戏决定。':'Type identifier such as Quests or Events. The game determines its runtime behavior.','权重，默认 10。':'Weight; defaults to 10.','冷却天数，默认 0。':'Cooldown in days; defaults to 0.','关联事件 Id 的文本数组，默认空数组。':'String array of linked event IDs; defaults to an empty array.','规则':'Rule','Periodic：按间隔天数；BySeason：按季节；ByDayInYear：按每年第几天。':'Periodic: an interval in days; BySeason: a season; ByDayInYear: a day of the year.','ByDayInYear 使用，默认 1。工坊输入范围 1–365，请依据游戏实际年长设置。':'Used by ByDayInYear; defaults to 1. The workshop accepts 1–365. Choose a day within the actual in-game year.','Spring / Summer / Autumn / Winter，默认 Spring。':'Spring / Summer / Autumn / Winter; defaults to Spring.','周期天数，默认 15，必须大于 0。':'Interval in days; defaults to 15 and must be positive.','持续天数，默认 1，必须大于 0。':'Duration in days; defaults to 1 and must be positive.',
'工坊会补齐游戏支持的缺省字段，下载时保留这些字段。未被游戏读取的额外字段不会保留在下载文件中。':'The workshop fills in supported default fields and retains them on download. Extra fields that the game does not read are not retained.','让别人发现你的作品':'Help others discover your creation','在':'On ','点击“分享我的作品”。':' select “Share my creation”.','填写名称、类型、介绍，选择 JSON 文件，并添加最多 5 个自定义标签。':'Enter a name, type and description, choose a JSON file and add up to 5 custom tags.','校验通过后打开 GitHub 发布草稿，登录账号并提交。':'After validation, open the GitHub draft, sign in and submit it.','返回广场刷新。作品详情可预览、下载并阅读评论。':'Return and refresh the community. Creation details include previews, downloads and comments.',
'标签存储在分享正文中，无需仓库标签权限。较长的 JSON 会提供可复制的发布正文，供你在 GitHub 中粘贴。发表评论使用详情中的“去 GitHub 评论”入口。':'Tags are stored in the post body, so repository label permissions are not needed. Longer JSON is provided as copyable text to paste into GitHub. Use “Comment on GitHub” to leave feedback.','旧分享若没有类型标签，可在原帖正文添加':'For older posts without a type label, add ','等标识。JSON 推荐放在':' or another type marker to the post body. Put JSON inside a ', '代码块中。没有可读取资产或格式校验未通过的帖子会禁用下载。':' code block. Downloads are disabled when a post has no readable library or fails validation.',
'下载后游戏里看不到资产？':'Why does the library not appear in the game?','确认后缀为 .json、子文件夹类型正确、内容使用 Items 或 Entries 对应结构，再重新打开库选择页面。当前目录名称与发行版可能不同。':'Check the .json extension, type folder and Items or Entries structure, then reopen the library selection screen. Folder names may differ in the release.','AI 生成失败或 JSON 校验失败？':'What if generation or JSON validation fails?','AI 不保证总能返回正确结构。检查具体错误提示，减少条目数、简化提示词后重试。预览中的手动编辑也必须保持合法 JSON。':'AI output is not guaranteed to have the right structure. Check the error, reduce the entry count or simplify the prompt and retry. Manual edits must also remain valid JSON.','为什么下载内容与原始 JSON 有些区别？':'Why does the download differ from the original JSON?','下载会校验、规范化空白并补齐游戏缺省字段，只保留游戏支持的字段。文件中预览的名称、描述与阶段内容会保留。':'Downloads validate the file, normalize formatting and add game defaults. Only supported fields are retained; your names, descriptions and stage content are preserved.','分享广场或评论加载失败？':'What if creations or comments fail to load?','浏览器需要访问 GitHub API。网络限制或 GitHub 的未登录请求额度都可能导致失败，可稍后重试或打开 GitHub 原帖查看。':'Your browser needs access to the GitHub API. Network restrictions or anonymous request limits may cause failures. Try again later or open the original GitHub post.','Steam 商店页在哪里？':'Where is the Steam store page?','目前还没有配置正式 Steam 商店链接。商店上线后，官网会提供直达入口。':'A Steam store link has not been configured yet. A direct link will appear when the store opens.','开始创造 ↗':'Start creating ↗','Grandpas Land 内容库生成、导入、分享指南与 JSON 字段说明。':'A guide to generating, importing and sharing Grandpas Land libraries, with JSON field references.',
'浏览器不允许本地保存，Key 将仅在本次页面中使用。':'Local storage is unavailable. The key will only be used during this visit.','已清除当前 Key 和此设备上的保存记录。':'The current key and saved key have been cleared.','AI 接口必须使用 HTTPS，且不能在地址中包含账号或密码':'The AI endpoint must use HTTPS and must not contain a username or password.','请填写模型名、API Key 和库名':'Enter a model, API key and library name.','请填写风格或内容描述':'Enter a style or content description.','请先生成资产':'Generate a library first.','灵感正在生长…':'Growing your ideas…','正在生成，通常需要 10–60 秒。':'Generating. This usually takes 10–60 seconds.','请检查 Key。':'Check your key.','请求过多或额度不足，请稍后重试。':'Too many requests or insufficient credits. Try again later.','服务暂时不可用，请稍后重试。':'The service is unavailable. Try again later.','请检查接口、模型名和账户权限。':'Check the endpoint, model and account permissions.','生成完成，格式已通过校验。可以编辑预览，下载会保存最新内容。':'Generated and validated. You can edit the preview; downloading saves your latest edits.','生成超过 90 秒，已停止等待。请减少数量或稍后重试。':'Generation took more than 90 seconds. Try fewer entries or retry later.','已取消本次生成。服务商可能已处理请求并产生费用。':'Generation canceled. Your provider may have already processed and charged for the request.','无法连接 AI 接口。请检查网络、接口地址及服务商是否允许浏览器跨域请求，详见使用文档。':'Cannot connect to the AI endpoint. Check your network, endpoint and provider’s browser cross-origin support. See the guide.',
'GitHub 请求额度暂时用尽，请稍后再试。':'The GitHub request limit has been reached. Try again later.','分享数据暂时不可用，请到社区原帖查看。':'Creation data is unavailable. Open the community on GitHub.','分享数据格式异常':'Unexpected creation data format.','暂时没有连接到分享广场':'Cannot connect to the community','请检查网络，或打开 GitHub 社区原帖。':'Check your network or open the community on GitHub.','重新加载':'Reload','全部标签':'All tags','换个关键词，发现新的灵感。':'Try another keyword for fresh ideas.','第一份灵感，等你种下。':'The first idea could be yours.','可以尝试其他类型、时间或标签。':'Try another type, date range or tag.','广场还没有可展示的作品。去工坊创作，再来分享你的世界。':'There are no creations yet. Make one in the workshop and share your world.','分享我的作品 ↗':'Share my creation ↗','查看作品 ↗':'View creation ↗','未知日期':'Unknown date','正在读取评论…':'Loading comments…','评论数据格式异常':'Unexpected comment data format.','还没有评论。到 GitHub 留下第一条反馈。':'No comments yet. Leave the first one on GitHub.','这里展示前 100 条评论，完整讨论请打开原帖。':'The first 100 comments are shown. Open the original post for the full discussion.','评论读取已停止，可到原帖查看。':'Comment loading stopped. Open the original post to read them.','评论暂时无法读取，请到原帖查看。':'Comments are unavailable. Open the original post.','这份分享尚未附上可读取的 JSON，请到原帖查看。':'This post has no readable JSON. Check the original post.',
'请选择 .json 文件':'Choose a .json file.','文件超过 1 MB':'The file exceeds 1 MB.','请填写作品名称和介绍':'Enter a creation name and description.','请使用最多 5 个标签，每个标签不超过 24 字，不能含尖括号':'Use up to 5 tags, each at most 24 characters, without angle brackets.','内容可能含有密钥，请删除后再分享':'The content may contain a key. Remove it before sharing.','分享内容过大，请拆成更小的库，或在 GitHub 原帖附上文件。':'The creation is too large. Split it into smaller libraries or attach the file on GitHub.','复制下方完整正文，在 GitHub 草稿中粘贴后提交':'Copy the full text below, paste it into the GitHub draft, then submit.','打开 GitHub 草稿 ↗':'Open GitHub draft ↗','格式通过校验。内容较长，请复制下方正文后打开 GitHub 草稿。':'Validated. Copy the longer post text below before opening the GitHub draft.','打开 GitHub 发布草稿 ↗':'Open GitHub publishing draft ↗','格式通过校验。点击下方按钮，到 GitHub 提交完成分享。':'Validated. Open the draft below and submit it on GitHub to finish sharing.',
'没有可读取的 JSON 内容':'There is no JSON content to read.','JSON 无法解析，请检查引号、逗号与括号':'Cannot parse JSON. Check quotes, commas and brackets.','AI 返回的内容不是文本':'The AI response is not text.','请选择支持的资产类型':'Choose a supported library type.','JSON 顶层必须是对象':'The JSON root must be an object.','文件同时包含 Items 和 Entries，请核对资产类型':'The file contains both Items and Entries. Check the library type.','单个库最多支持 5000 个条目':'A library can contain at most 5000 entries.','名字重复，请删除重复项':'Names are duplicated. Remove duplicates.'
};
const fragments={
'AI 服务返回 HTTP ':'AI service returned HTTP ','AI 返回 ':'AI returned ',' 个条目，与要求的 ':' entries instead of the requested ',' 个不一致，请减少数量后重试':' entries. Try requesting fewer entries.','格式通过校验，共 ':'Validated: ',' 个条目。':' entries.',' 个条目':' entries','已下载预览中的最新内容：':'Downloaded the latest preview: ',' 份灵感':' creations',' · 当前展示最近 1000 条记录范围内的作品':' · Showing creations from the latest 1,000 records',' 条评论':' comments','GitHub 返回 HTTP ':'GitHub returned HTTP ','，请稍后重试。':'. Try again later.','条目 Id 重复：':'Duplicate entry ID: ','条目 ':'Entry ','第 ':'Name ',' 个名字':'',' 必须是文本':' must be a string',' 不能为空':' cannot be empty',' 超过 ':' exceeds ',' 个字符':' characters',' 必须是 ':' must be an integer between ',' 的整数':'',' 的值无效':' has an invalid value','必须是对象':'must be an object','Stages 必须是数组':'Stages must be an array','阶段数量过多':'Too many stages','阶段必须是对象':'A stage must be an object','阶段描述':'stage description',' 名称':' name','阶段 ':'Stage ','LinkedEventIds 必须是数组':'LinkedEventIds must be an array','关联事件数量过多':'Too many linked events','关联事件 Id':'Linked event ID','需要非空的 ':'Requires a nonempty ',' 数组':' array','[Key 已隐藏]':'[key hidden]','请求失败':'Request failed'
};
en['生成我的资产 ↗']='Generate my library ↗';
Object.assign(en,{
'支线库 · 草稿':'Quests · Drafts','特定 NPC 库 · 草稿':'Special NPCs · Drafts',
'每份分享包含一个 JSON 库；超出正文容量请拆分。当前广场不能读取附件。发布后刷新查看。':'Each post contains one JSON library. Split files that exceed the post capacity. Attachments cannot be read by this gallery. Refresh after publishing.',
'名字库可以用于生成世界。事件库通过 TriggerConsequences 调用现有子效果，节日库可触发关联事件。支线和特定 NPC 库目前仅能导入保存，尚未接通外部条目的执行入口。':'Name libraries are used to generate worlds. Event libraries invoke existing effects through TriggerConsequences, and festivals can trigger linked events. Quest and special NPC libraries can currently be imported and saved, but do not yet have external execution paths.',
'在游戏库选择页面导入 JSON，或放入对应类型的文件夹，再创建世界。':'Import the JSON in the game library selector, or put it in the matching type folder, then create a world.',
'创建世界时每种类型选择一个库，内容会保存为存档快照。更新外部文件不会自动改写已有世界。节日关联的事件库也必须同时选择。联机时由主机加载和执行这些数据，客户端接收结果；下载者不需要作者的 AI Key。':'Select one library per type when creating a world. Its contents are saved as a snapshot, so updating external files does not rewrite an existing world. Also select any event library referenced by a festival. The multiplayer host loads and executes this data; clients receive the results. Downloaders do not need the author’s AI key.',
'事件、节日、支线和特定 NPC 共用 Entries，字段名区分大小写。以下阶段示例属于草稿；故事描述本身不执行效果。':'Events, festivals, quests and special NPCs share Entries, with case-sensitive fields. The staged example below is a draft; descriptions alone do not execute effects.',
'旧内容处理器标识，默认空文本。文件夹和分享类型决定库类别，不能用它覆盖原有处理器。':'Legacy content handler identifier, empty by default. Folders and the sharing type determine the library category; do not overwrite a handler with that category.',
'ByDayInYear 使用，默认 1。兼容目录中的当前默认年长为 3 天，日期不得超过实际游戏年长。':'Used by ByDayInYear, defaulting to 1. This compatibility profile uses a 3-day year; the day must fit the actual game calendar.',
'校验会保留支持的目标、子效果、选项和阶段字段，并补齐缺省值。未知字段和未注册效果会报错，避免在下载时悄悄丢失行为。结构和参数通过校验，仍需在实际游戏中确认运行结果。':'Validation preserves supported targets, effects, options and stages and adds defaults. Unknown fields and unregistered effects cause errors instead of silently losing behavior. Structure and parameter checks still require in-game verification.',
'下载会规范化空白并补齐缺省值，保留预览中支持的名字、描述、阶段、目标和子效果。未知字段会报错，不会静默删除。':'Downloads normalize formatting and add defaults while preserving supported names, descriptions, stages, targets and effects. Unknown fields are rejected instead of silently removed.',
'可执行事件：组合现有子效果':'Executable events: compose existing effects',
'完整事件通过 Target 选择地点，再组合 TriggerConsequences 中的效果。下面的事件随机选择一座城市，感染其中的 NPC 并提高当地药材需求；瘟疫和药材标签必须存在于所用游戏版本。':'Complete events choose a location through Target and compose effects in TriggerConsequences. This example picks a random city, infects NPCs there and raises demand for medicinal materials. The disease and item tag must exist in the game version being used.',
'完整事件通过 Target 选择地点，再组合 TriggerConsequences 中的效果。下面的事件随机选择一座城市，减少其中三名 NPC 的健康，并提高当地已有匕首物品的需求。':'Complete events choose a location through Target and compose effects in TriggerConsequences. This example picks a random city, reduces the health of three NPCs and raises demand for an existing dagger item.',
'当前兼容目录尚未列出疾病定义，物品标签列表也为空。瘟疫 Buff 和按药材标签涨价的事件需要先在游戏中配置相应资源，再重新导出兼容目录；生成器不能自行创建这些资源。':'The current profile has no disease definitions and an empty item tag list. Plague buffs and events affecting medicinal-material tags require those resources to be configured in the game and the profile to be exported again. The generator cannot create those resources itself.',
'用途':'Purpose','可选的文件协议与游戏兼容目录标识，新生成事件会携带这两个值。':'Optional file protocol and game profile identifiers; newly generated events include them.',
'事件地点与角色上下文，可随机选择城市。角色目标由各子效果筛选，支持 NPC 或玩家。':'Event location and character context, including random city selection. Each effect filters its character targets, supporting NPCs or players.',
'立即执行的效果数组，每项使用已注册的 Type、Parameters，可用容器的 Children 组合。':'Effects executed immediately. Each uses a registered Type and Parameters; container effects can compose Children.',
'可选的交互选项；普通世界事件使用空数组即可，不要求玩家选择。':'Optional interactive choices. Ordinary world events can use an empty array without requiring a player decision.',
'事件评价与分类信息，枚举值由游戏兼容目录约束。':'Event evaluation and categories; enum values are constrained by the game profile.',
'是否允许再次触发；仍受冷却规则约束。':'Whether the event may trigger again, subject to cooldown rules.',
'分享给其他世界时，优先使用随机城市、城内角色筛选和 {SettlementName} 占位符。固定 ActorId、PlayerId、SettlementId 通常只适用于特定存档。AI 不能仅凭名称创建新疾病、物品或执行代码。目录资源不完整时会显示警告，需要在游戏中确认引用。':'For sharing across worlds, prefer random cities, settlement character filters and the {SettlementName} placeholder. Fixed ActorId, PlayerId and SettlementId usually apply only to a specific save. AI cannot create new diseases, items or executable code merely by naming them. Incomplete resource catalogs produce warnings and require reference checks in the game.',
'每份分享包含一个 JSON 库；超过正文容量需拆分，当前广场不读取附件。关联节日与事件应分别分享，并在介绍中注明另一份库的链接。作品更新应保持事件 Id 稳定，复制为新作品时请使用新的 Id，避免关联混淆。':'Each post contains one JSON library. Split libraries that exceed the post capacity; the gallery does not read attachments. Share linked festival and event libraries separately and link them in the descriptions. Preserve event IDs when updating a creation; use new IDs when making a separate work to avoid ambiguous references.'
});
const escaped=Object.keys(fragments).sort((a,b)=>b.length-a.length).map(s=>s.replace(/[.*+?^${}()|[\]\\]/g,'\\$&'));
const fragmentPattern=new RegExp(escaped.join('|'),'g');
const textState=new WeakMap(),attributeState=new WeakMap();
let lang='zh-CN',observer;
try{const stored=localStorage.getItem('gl_language');if(stored==='en'||stored==='zh-CN')lang=stored;}catch{}
const urlLanguage=new URLSearchParams(location.search).get('lang');if(urlLanguage==='en'||urlLanguage==='zh-CN'){lang=urlLanguage;try{localStorage.setItem('gl_language',lang);}catch{}}
function t(source){if(lang!=='en')return source;if(Object.hasOwn(en,source))return en[source];return source.replace(fragmentPattern,match=>fragments[match]);}
function ignored(el){return !el||el.closest('script,style,pre,code,textarea,[data-i18n-ignore]');}
function translateText(node){if(ignored(node.parentElement))return;let state=textState.get(node);if(!state||node.nodeValue!==state.last){state={source:node.nodeValue,last:node.nodeValue};textState.set(node,state);}const trimmed=state.source.trim();const translated=t(trimmed);const leading=state.source.match(/^\s*/)[0],trailing=state.source.match(/\s*$/)[0];const next=trimmed?leading+translated+trailing:state.source;if(node.nodeValue!==next)node.nodeValue=next;state.last=next;}
function apply(){
  if(observer)observer.disconnect();document.documentElement.lang=lang;
  const walker=document.createTreeWalker(document.documentElement,NodeFilter.SHOW_TEXT);while(walker.nextNode())translateText(walker.currentNode);
  for(const el of document.querySelectorAll('[placeholder],[aria-label],[alt],meta[name="description"]')){
    if(el.closest('[data-i18n-ignore]'))continue;let states=attributeState.get(el);if(!states){states={};attributeState.set(el,states);}
    for(const attr of ['placeholder','aria-label','alt','content']){if(!el.hasAttribute(attr))continue;const value=el.getAttribute(attr);let state=states[attr];if(!state||value!==state.last)state=states[attr]={source:value,last:value};const next=t(state.source);if(value!==next)el.setAttribute(attr,next);state.last=next;}
  }
  const select=document.getElementById('siteLanguage');if(select)select.value=lang;
  if(observer)observer.observe(document.documentElement,{subtree:true,childList:true,characterData:true});
}
function setLanguage(value,persist=true){if(value!=='en'&&value!=='zh-CN')return;lang=value;if(persist){try{localStorage.setItem('gl_language',lang);}catch{}const address=new URL(location.href);if(address.searchParams.has('lang')){address.searchParams.set('lang',lang);history.replaceState(null,'',address);}}apply();window.dispatchEvent(new CustomEvent('gl-languagechange',{detail:lang}));}
window.GLI18n={t,setLanguage,get language(){return lang;}};
function start(){const select=document.getElementById('siteLanguage');if(select)select.addEventListener('change',event=>setLanguage(event.target.value));observer=new MutationObserver(apply);apply();}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();
window.addEventListener('storage',event=>{if(event.key==='gl_language')setLanguage(event.newValue,false);});
})();
